### ISSUE TITLE
DOI information for published Algorithms, Remarks and Certifications

### ISSUE THREAD

**Issue by TimHopkins** [ACM-TOMS/CALGO#13]
CALGOdois.txt contains records that include the last component of the DOIs for all CALGO Algorithm articles along with Remark and Certification articles that have appeared in both CACM, TOMS and TOPLAS. The README.txt file contains a description of the format of the file.

[CALGOdois.txt](https://github.com/ACM-TOMS/CALGO/files/8425698/CALGOdois.txt)
[README.txt](https://github.com/ACM-TOMS/CALGO/files/8425700/README.txt)
.

**Comment by pauldj** [comment]
1) The file CALGOdois.txt contains DOIs for algorithms, remarks, and certifications. I assume we are only concerned with algorithms here. Btw, what are certifications?

2) CALGOdois.txt contains the suffix of the DOIs. Is the prefix (10.1145) the same for all algorithms? 

3) A couple of entries are jumbled together:
00905A toms 2010 sep 37  3     20--20  01019A toms 2022 mar 48  1     36--36             3495005
01019A toms 2022 mar 48  1     31--31             3478686   1824801.1824812

I can try to recover them by hand.

**Comment by pauldj** [comment]
How do we call the file that will contain the DOI?
- DOI
- DOI.txt
- xyzw.DOI   
-  .... ?

**Comment by bangerth** [comment]
Let's call the file `DOI.txt`. I keep running into folks who don't know what to do with files without extension :-)

**Comment by bangerth** [comment]
This is fixed by #29.
