### ISSUE TITLE
Replacement Contents for Algorithm 620

### ISSUE THREAD

**Issue by TimHopkins** [ACM-TOMS/CALGO#17]
Algorithm 620 contains bibliographic data for each algorithm and is updated following the appearance of each new ALgorithm, Remark, etc.
The files that change are:
Bib/620.bib and Dbase/DBase.txt
The second of these contains a compressed record of the publication details of all the CALGO algorithms, Remarks, etc. From this we can derive a Bibtex database file for all the Algorithms (Bib/620.bib).
There is some (very) old Fortran code that is obsolete (I think!) so only these two files are really relevant.

This needs some work doing on it which possibly isn't worthwhile.

[620.zip](https://github.com/ACM-TOMS/CALGO/files/8425954/620.zip)

**Comment by bangerth** [comment]
Fixed by #36.
