### ISSUE TITLE
Move contents of every directory into a subdirectory

### ISSUE THREAD

**Issue by bangerth** [ACM-TOMS/CALGO#18]
If we want to create subdirectories under `xxxx/`, like `xxxx/meta/` (see #10, #13) or to store updated versions of algorithms (see #16), then we should probably move everything that is under `xxxx/` currently one level down, say into `xxxx/submitted_code/`.

Thoughts about that? Is that a good name?

**Comment by bangerth** [comment]
Separately, that would also free us to put a file `xxxx/Readme.md` into each directory (see #12) without the potential of stepping onto existing files of that name.

**Comment by pauldj** [comment]
solved by PR #23
