### ISSUE TITLE
"paths colliding" on cloning

### ISSUE THREAD

**Issue by pauldj** [ACM-TOMS/CALGO#19]
There are a handful of cases of files that cause (in git lingo) "path colliding", i.e., "case-sensitive paths on a case-insensitive filesystem". In other words, there are files that only differ in lower/upper cases. 

Namely:
  '0806/DOCS/www/examples/sprng-simple_mpi.C'
  '0806/DOCS/www/examples/sprng-simple_mpi.c'
  '0806/DOCS/www/examples/sprng.C'
  '0806/DOCS/www/examples/sprng.c'
  '0806/EXAMPLES/sprng-simple_mpi.C'
  '0806/EXAMPLES/sprng-simple_mpi.c'
  '0806/EXAMPLES/sprng.C'
  '0806/EXAMPLES/sprng.c'
  '0850/Fortran90/Dp/Drivers/Res'
  '0850/Fortran90/Dp/Drivers/res'

**Comment by bangerth** [comment]
Ah, that's pretty unfortunate. Are these files actually different? If not -- that is, if this is likely some kind of accident -- then we could just remove one. It's hard to believe that someone would have both a `.c` and a `.C` file with different contents in their directories...

**Comment by bangerth** [comment]
I looked at the files in the `0806/` directory:
```{diff}
> diff -w 0806/EXAMPLES/sprng-simple_mpi.*
2c2
< /*           Demonstrates sprng use with one stream per process            */
---
> /*           Demonstrates sprng use in C++ with MPI                        */
9c9
< #include <mpi.h>                /* MPI header file                         */
---
> #include <mpi.h>                // MPI header file
11,13c11,13
< #define SIMPLE_SPRNG          /* simple interface                        */
< #define USE_MPI                       /* use MPI to find number of processes     */
< #include "sprng.h"              /* SPRNG header file                       */
---
> #define SIMPLE_SPRNG          // simple interface 
> #define USE_MPI                       // use MPI to find number of processes
> #include "sprng.h"              // SPRNG header file
```
So this one is functionally equivalent.

Then this:
```{diff}
 diff -w 0806/EXAMPLES/sprng.[cC]
2c2
< /*            ____Demonstrates the use of sprng and isprng____             */
---
> /*            ____Demonstrates the use of sprng in C++____                 */
4c4
< /* numbers and a few integers are printed.                                 */
---
> /* numbers are printed.                                                    */
6,10c6,7
< 
< #include <stdio.h>
< 
< /* Uncomment the following line to get the interface with pointer checking */
< /*#define CHECK_POINTERS                                                   */
---
> #include <string.h>
> #include <iostream.h>
31c28
<   printf(" Print information about new stream:\n");
---
>   cout << " Print information about new stream:\n";
36c33
<   printf(" Printing 3 random numbers in [0,1):\n");
---
>   cout << " Printing 3 random numbers in [0,1):\n";
40c37
<     printf("%f\n",rn);
---
>     cout << rn << "\n";
42,50d38
< 
<   printf(" Printing 3 random integers in [0,2^31):\n");
<   for (i=0;i<3;i++)
<   {
<     irn = isprng(stream);     /* generate an integer random number */
<     printf("%16d\n",irn);
<   }
< 
<   /*************************** free memory ********************************/
```
This is also functionally equivalent, at least in essence.

The files in the `DOCS/www/examples/` directory are duplicates of the files in the `EXAMPLES/` directory. 

One solution might be to just rename all `.C` files to `.cc` as is common practice in the C++ community, or to `.cpp`.

**Comment by bangerth** [comment]
For the `0850/` directory, the two files in question are identical.

**Comment by bangerth** [comment]
The `0850/` directory has an explanation of what the two files are supposed to be if you look at the file `Fortran90/Dp/Drivers/Makefile`:
```
%.o : %.f90
	$(F77) $(F77OPTS) -c $*.f90

all: Res

SRCLIBS= 

DRIVERS= driver
RESULTS= Res

Objs= driver.o air.o cons.o parab.o
driver: $(Objs)
	$(F77) $(F77OPTS) -o driver $(Objs) $(SRCLIBS)
Res: driver
	./driver >Res

air.o: cons.o

cons.o:

driver.o: cons.o parab.o

parab.o: cons.o air.o

diffres: Res res
	echo "Differences in results from driver"
	$(DIFF)  Res res

clean: 
	rm -rf *.o $(DRIVERS) $(CLEANUP) $(RESULTS)
```
So one of the files is a saved output (`res`) and the other one is supposed to be the result of a test run (`Res`) that is then compared against the saved output. This is not good style, but it would be easy to rename `res` to `Res.correct` or `Res.verified` or some such. Should I do that?

**Comment by pauldj** [comment]
So in summary:
- In 0806/, the conflicting .C files can be renamed .cpp
- In 0850/, either the file res is renamed, or Res becomes something else, i.e., "result".
If you don't mind, please go ahead. (This should save me a headache.) Thanks!

**Comment by bangerth** [comment]
@pauldj This is now fixed, right? I'll close it, but feel free to re-open if necessary.
