### ISSUE TITLE
Preserve original submission in a subdirectory

### ISSUE THREAD

**Issue by bangerth** [ACM-TOMS/CALGO#5]
Like @TimHopkins states:

> These files are the original submissions (or what was saved of the original submissions at the time) for all the algorithms that were published in TOMS (493 onwards) along with a few of the later codes published in CACM. Added to these are a number of CACM published codes that have been re-keyed or translated by researchers who are good enough to donate their copies to me.
>
> This, is therefore, the ACM archive and needs to be preserved in this warts-and-all form, i.e., any changes, upgrades, etc. need to be applied to a copy.
>
> The first thing we need to decide upon is a directory structure for each algorithm and, as a first step, we then update the current file system to this new structure.
>
> My feeling is that we keep the top level “algorithm number“ directories and then generate a subdirectory, say, OriginalSub, into which we move the files already on GitHub. 

My suggestion would be to have a directory structure like this:
```
  1-100/
   |
   L----42/
            |
            L-----meta/
                    original-submission/
                    .../
```
where `original-submission/` refers to the original files as currently stored in each directory, `meta/` contains meta-data (e.g. DOIs, bibtex entries, copyright information, etc.). Modifications can then be stored in further parallel directories, as can be translations into other languages.

**Comment by pauldj** [comment]
Solved in PR #23
